Recipe/Models/Formula.cs
using System.Collections.Generic;
using System;
using System.Data;
using System.Diagnostics;

namespace Recipe.Models
{
    public class Formula
    {
        public Formula()
        {
            this.JoinEntities = new HashSet<Box>();
        }

        public int FormulaId { get; set; }
        public string FormulaName { get; set; }
        public string Ingredients { get; set; }
        public string Instructions { get; set; }
        public int Rating { get; set; }
        public virtual ApplicationUser User { get; set; }

        public virtual ICollection<Box> JoinEntities { get;}

        public string[] ListIngredients (string Ingredients)
        {
          string[] Ing = Ingredients.Split(',');
          return Ing;
          
        }
    
    }
}

Recipe/Controllers/FormulasController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Recipe.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace Recipe.Controllers
{
  [Authorize]
  public class FormulasController : Controller
  {
    private readonly RecipeContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public FormulasController(UserManager<ApplicationUser> userManager, RecipeContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public async Task<ActionResult> Index()
    {
        var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        var currentUser = await _userManager.FindByIdAsync(userId);
        var userFormulas = _db.Formulas.Where(entry => entry.User.Id == currentUser.Id).OrderByDescending(model => model.Rating).ToList();
        return View(userFormulas);
    }

    public ActionResult Create()
    {
      ViewBag.TagId = new SelectList(_db.Tags, "TagId", "TagName");
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Formula formula, int TagId)
    {
        var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        var currentUser = await _userManager.FindByIdAsync(userId);
        formula.User = currentUser;
        _db.Formulas.Add(formula);
        _db.SaveChanges();
        if (TagId != 0)
        {
            _db.Box.Add(new Box() { TagId = TagId, FormulaId = formula.FormulaId });
        }
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisFormula = _db.Formulas
        .Include(formula => formula.JoinEntities)
        .ThenInclude(join => join.Tag)
        .FirstOrDefault(formula => formula.FormulaId == id);
      return View(thisFormula);
    }

    public ActionResult Edit(int id)
    {
        var thisFormula = _db.Formulas.FirstOrDefault(formula => formula.FormulaId == id);
        ViewBag.TagId = new SelectList(_db.Tags, "TagId", "TagName");
        return View(thisFormula);
    }

    [HttpPost]
    public ActionResult Edit(Formula formula, int TagId)
    {
      if (TagId != 0)
      {
        _db.Box.Add(new Box() { TagId = TagId, FormulaId = formula.FormulaId });
      }
      _db.Entry(formula).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddTag(int id)
    {
        var thisFormula = _db.Formulas.FirstOrDefault(formula => formula.FormulaId == id);
        ViewBag.TagId = new SelectList(_db.Tags, "TagId", "TagName");
        return View(thisFormula);
    }

    [HttpPost]
    public ActionResult AddTag(Formula formula, int TagId)
    {
        if (TagId != 0)
        {
          _db.Box.Add(new Box() { TagId = TagId, FormulaId = formula.FormulaId });
          _db.SaveChanges();
        }
        return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisFormula = _db.Formulas.FirstOrDefault(formula => formula.FormulaId == id);
      return View(thisFormula);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisFormula = _db.Formulas.FirstOrDefault(formula => formula.FormulaId == id);
      _db.Formulas.Remove(thisFormula);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteTag(int joinId)
    {
        var joinEntry = _db.Box.FirstOrDefault(entry => entry.BoxId == joinId);
        _db.Box.Remove(joinEntry);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
  }
}

Recipe/Views/Formulas/AddTag.cshtml
@{
  Layout = "_Layout";
}

@model Recipe.Models.Formula

<h1 class="img">Add a tag</h1>

<h4>Add a tag to this recipe: @Html.DisplayFor(model => model.FormulaName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.FormulaId)

    @Html.Label("Select tag")
    @Html.DropDownList("TagId")

    <input type="submit" value="Save" class="accept"/>
}

<p>@Html.ActionLink("Back to list", "Index", new { area = "" }, new { @class = "accept" })</p>

Recipe/Views/Formulas/Create.cshtml
@{
  Layout = "_Layout";
}

@model Recipe.Models.Formula

<h1 class="img">Add a new Recipe</h1>

@using (Html.BeginForm())
{
    @Html.Label("Recipe Name: ")
    <br>
    <div class="create">@Html.TextBoxFor(model => model.FormulaName, new { style = "width: 90%;"})</div>
    <br>
    @Html.LabelFor(model => model.Ingredients)
    <p>Format: quantity ingredient, <br>---dont forget to pace commas between each ingredient </p>
    <br>
    <div class="create"> @Html.TextAreaFor(model => model.Ingredients, new { @rows=5, style = "width: 90%;" })</div>
    <br>
    @Html.LabelFor(model => model.Instructions)
    <br>
    <div class="create"> @Html.TextAreaFor(model => model.Instructions, new { @rows=10, style = "width: 90%;" })</div>
    <br>
    @Html.Label("Select tag: ")
    @Html.DropDownList("TagId")
    <br>
    for(int i = 1; i < 11; i++)
    {
      <input type="radio" id="Rating" name="Rating" value="@i" />@i
    }
    <br>
    <input type="submit" value="Add new recipe" class="accept" />
    <br>
}

<br>
<p>@Html.ActionLink("Show all recipes", "Index", new { area = "" }, new { @class = "accept" })</p>

Recipe/Views/Formulas/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Recipe.Models.Formula

<h1 class="img">Are you sure you want to delete this?</h1>

@Html.Label("Recipe:  ") @Html.DisplayFor(model => model.FormulaName)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" class="delete"/>
}
<br>
@Html.ActionLink("Back to List", "Index", new { area = "" }, new { @class = "accept" })

Recipe/Views/Formulas/Details.cshtml
@{
  Layout = "_Layout";
}

@model Recipe.Models.Formula;


<h1 class="img">Recipe Details</h1>
<hr />
<h3>@Html.Label("Recipe Name"): @Html.DisplayFor(model => model.FormulaName)</h3>
<h3>@Html.Label("Rating 1-10: ") @Html.DisplayFor(model => model.Rating)</h3>
<h5>@Html.LabelFor(model => model.Ingredients):</h5>


<ul>
@foreach(var Ing in Model.ListIngredients(Model.Ingredients))
{
  <li>@($"{Ing}")</li>
}
</ul>


<h5>@Html.LabelFor(model => model.Instructions):</h5>
  <br>
  <p>@Html.DisplayFor(model => model.Instructions)
</p>



@if(@Model.JoinEntities.Count == 0)
{
  <p>This recipe doesn't have any tags</p>
}
else
{
  <h4>Tags this recipe belongs to:</h4>
  <ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li>@join.Tag.TagName</li>
    @using (Html.BeginForm("DeleteTag", "Formulas"))
    {
      @Html.Hidden("joinId", @join.BoxId)
      <input type="submit" value="Delete" class="delete" />
    }
  }
  </ul>
}

<p>@Html.ActionLink("Back to list", "Index", new { area = "" }, new { @class = "accept" })</p>
<p>@Html.ActionLink("Edit Recipe", "Edit", new { id = Model.FormulaId }, new { @class = "accept" })</p>
<p>@Html.ActionLink("Delete Recipe", "Delete", new { id = Model.FormulaId }, new { @class = "accept" })</p>

Recipe/Views/Formulas/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Recipe.Models.Formula

<h1 class="img">Edit</h1>

<h4>Edit this recipe: @Html.DisplayFor(model => model.FormulaName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.FormulaId)
    <br>
    @Html.LabelFor(model => model.FormulaName)
    @Html.EditorFor(model => model.FormulaName)
    <br>
    @Html.LabelFor(model => model.Ingredients)
    @Html.EditorFor(model => model.Ingredients)
    <br>
    @Html.LabelFor(model => model.Instructions)
    @Html.EditorFor(model => model.Instructions)
    <br>
    @Html.Label("Select tag")
    @Html.DropDownList("TagId")
    <br>
    <br>
    for(int i = 1; i < 11; i++)
    {
      <input type="radio" id="Rating" name="Rating" value="@i" />@i
    }
    <br>
    <input type="submit" value="Save" class="accept" />
}
<br>
<p>@Html.ActionLink("Back to list", "Index", new { area = "" }, new { @class = "accept" })</p>

Recipe/Views/Formulas/Index.cshtml
@{
  Layout = "_Layout";
}

@using Recipe.Models;
@model IEnumerable<Recipe.Models.Formula>

<h1  class="img">Recipes for @User.Identity.Name</h1>
<h6>Rating | Recipe Name </h6>
@if (Model.Any())
{
  <ul>
    @foreach (Formula formula in Model)
    {
      <li>@formula.Rating | @Html.ActionLink($"{formula.FormulaName}", "Details", new { id = formula.FormulaId }, new { @class = "name" })</li>
    }
  </ul>
} 
else
{
  <h3>No recipes have been added yet!</h3>
}

<p>@Html.ActionLink("Add new recipe", "Create", new { area = "" }, new { @class = "accept" })</p>

<p>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "accept" })</p>